# Generated by Django 4.2.2 on 2023-06-18 20:07

import MyPlant_App.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[MyPlant_App.accounts.models.validate_capitalized])),
                ('last_name', models.CharField(max_length=20, validators=[MyPlant_App.accounts.models.validate_capitalized])),
                ('profile_picture', models.URLField()),
            ],
        ),
    ]
